---
# Decent environment and settings for the users (/etc/skel)

- name: debug ansible bullshit
  debug: msg='/etc/skel/{{ item.path | regex_replace( "(^|/)dot-", "\1.") }}'
  with_filetree: '../templates/etc/skel'
  tags:
    - skel

- name: Ensure directory structure exists
  file:
    path: '/etc/skel/{{ item.path | regex_replace( "(^|/)dot-", "\1.") }}'
    state: directory
  with_filetree: '../templates/etc/skel'
  when: item.state == 'directory'
  tags:
    - skel

- name: Ensure files are populated from templates
  template:
    src: '{{ item.src }}'
    dest: '/etc/skel/{{ (item.path | regex_replace( "(^|/)dot-", "\1.") | splitext)[0] }}'
  with_filetree: ../templates/etc/skel
  when: item.state == 'file'
  loop_control:
    label: "{{ item.path }}"
  tags:
    - skel
