---
# Decent environment and settings for the maintainer (root)

- set_fact:
    inputrc_block: "{{ lookup('template', 'templates/etc/inputrc.j2') }}"
    bashrc_block: "{{ lookup('template', 'templates/etc/bash.bashrc.j2') }}"

- name: update inputrc
  blockinfile: path=/etc/inputrc group=root owner=root mode=0644 state=present block='{{ inputrc_block }}'

- name: update bashrc
  blockinfile: path=/etc/bash.bashrc group=root owner=root mode=0644 state=present block='{{ bashrc_block }}'

# vimrc is a new file
- name: vimrc
  template: src=etc/vimrc.j2 dest=/etc/vimrc

# exrc is a new file
- name: exrc
  template: src=etc/exrc.j2 dest=/etc/exrc

- name: less
  template: src=etc/profile.d/less.sh.j2 dest=/etc/profile.d/less.sh

- name: manpager
  template: src=etc/profile.d/man.sh.j2 dest=/etc/profile.d/man.sh

- name: bash completion
  template: src=etc/profile.d/completion.sh.j2 dest=/etc/profile.d/completion.sh

- name: systemd env
  template: src=etc/profile.d/systemd.sh.j2 dest=/etc/profile.d/systemd.sh

#- name: sudo

