---
# Modify docker for running on a /var/lib/docker that is a network filesystem

- name:    Configure docker for iscsi
  copy:    src=docker-on-iscsi.conf    mode=0644 dest=/etc/systemd/system/docker.service.d/
  notify:  docker-restarted

- name:    Configure overlay watcher service
  copy:    src=overlay-watcher.service mode=0644 dest=/etc/systemd/system/
  notify:  docker-restarted

- name:    Configure overlay watcher script
  copy:    src=overlay-watcher.sh      mode=0755 dest=/root/
  notify:  docker-restarted

- name:    enable overlay watcher
  systemd: name=overlay-watcher.service daemon_reload=yes enabled=yes state=started
  notify:  docker-restarted

- meta:    flush_handlers
