---
# install and set up docker

#- name: download new issue file
#  get_url:
#    url: http://config.example.com/issue
#    dest: /etc/issue

# Install docker and start a service that will be using the docker
# partition during a shutdown

- name: install requirements for ansible docker support
  apt:
    name:
      - python3-docker
      - python3-requests
      - python3-requestsexceptions
    state: present

- name: Install docker
  apt: state=present name=docker.io
  notify: docker-restarted

- meta: flush_handlers
