---
# set up iscsi and prepare docker storage on it

- name: Install packages
  apt:
    name:
      - open-iscsi
      - xfsprogs
  register: packages

- name: Install iscsi discovery systemd unit
  copy: src=open-iscsi-discovery.service mode=0644 dest=/etc/systemd/system
  register: iscsi_services

- name:     determine scsi portal which is the host IP ie the gateway
  shell:    ip route | egrep default.via | awk '{print $3}'
  register: PORTAL
  changed_when: false

- name:       add portal to host file
  lineinfile: create=no state=present path=/etc/hosts line="{{PORTAL.stdout}} portal"
  when:       'PORTAL != ""'
  register:   portal_var

- name:    enable
  systemd: name={{item}} daemon_reload=yes enabled=yes state=restarted
  with_items:
    - open-iscsi.service
    - open-iscsi-discovery.service
  when: iscsi_services.changed or portal_var.changed

