---
# tasks file for playbooks/roles/example

# - include_tasks: '{{stupid_ansible_var}}'
#   loop_control:
#     loop_var: stupid_ansible_var
#   loop:
#     - apt-setup.yml
#     - deactivate-vbox.yml
#     - setup-qemu-guest.yml
#     - setup-console.yml
#     - setup-networkd.yml
#     - rebuild-initrd.yml
#     - setup-iscsi.yml
#     - setup-docker.yml
#     - long-runner.yml

- include_tasks: apt-setup.yml
  tags: apt-setup
- include_tasks: deactivate-vbox.yml
  tags: vm-guest
- include_tasks: setup-qemu-guest.yml
  tags: vm-guest
- include_tasks: setup-console.yml
  tags: console
- include_tasks: setup-networkd.yml
  tags: network
- include_tasks: setup-iscsi.yml
  tags: iscsi
- include_tasks: setup-guest-docker.yml
  tags: guest-docker
- include_tasks: setup-docker.yml
  tags: docker
- include_tasks: long-runner.yml
  tags: docker
