---
# install and set up docker

#- name: download new issue file
#  get_url:
#    url: http://config.example.com/issue
#    dest: /etc/issue

# Install docker and start a service that will be using the docker
# partition during a shutdown

- name: Install docker
  apt: state=present name=docker.io

- name: install requirements for ansible docker support
  apt:
    name:
      - python3-docker
      - python3-requests
      - python3-requestsexceptions
    state: present

- name: Configure docker for iscsi
  copy: src=docker-dropin.conf mode=0644 dest=/etc/systemd/system/docker.service.d/

- name: Configure overlay watcher service
  copy: src=overlay-watcher.service mode=0644 dest=/etc/systemd/system/

- name: Configure overlay watcher script
  copy: src=overlay-watcher.sh mode=0755 dest=/root/

- name: enable and start docker
  systemd: name=docker.service daemon_reload=yes enabled=yes state=started

- name: enable overlay watcher
  systemd: name=overlay-watcher.service daemon_reload=yes enabled=yes state=started
